---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-51
ratings:
  paths:
    - lib/
exclude_paths:
  - spec/
  - vendor/
