language: ruby
cache: bundler
rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
  slack: sixtwothree:yATLmjTW15443qR7jbCWr3RO
